version: 2
jobs:
  build:
    docker:
      - image: cimg/node:15.0.1-browsers
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - setup_remote_docker:
          docker_layer_caching: true 

      - run: 
          name: Install dependencies
          command: |
            npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: 
          name: Build
          command: |
            docker build --rm=false -t ruiramossite .

      - run: 
          name: Install gcloud
          command: |
            sudo apt-get update && sudo apt-get install apt-transport-https && sudo apt-get install ca-certificates gnupg
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl -O https://packages.cloud.google.com/apt/doc/apt-key.gpg
            sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add apt-key.gpg
            sudo apt-get update && sudo apt-get install google-cloud-sdk

      - run: 
          name: Setup gcloud and docker
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json --project=vernal-mantra-665
            gcloud auth configure-docker --quiet

      - run:
          name: Pushing image
          command: |
            docker tag ruiramossite gcr.io/vernal-mantra-665/ruiramossite:build-$CIRCLE_BUILD_NUM
            docker push gcr.io/vernal-mantra-665/ruiramossite


